# Generated by Django 3.1.5 on 2021-01-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorByLine', models.CharField(max_length=30)),
                ('headline', models.CharField(max_length=100)),
                ('promo', models.CharField(max_length=100)),
            ],
        ),
    ]
