# Generated by Django 3.1.5 on 2021-01-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210110_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featuredImage',
            field=models.URLField(default='test'),
            preserve_default=False,
        ),
    ]
