# Generated by Django 3.1.5 on 2021-01-17 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210117_0221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instruments',
            new_name='Instrument',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
