# Generated by Django 3.1.5 on 2021-01-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210117_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uuid',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
