# Generated by Django 3.1.5 on 2021-01-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=3),
            preserve_default=False,
        ),
    ]
